# Copyright 2020 Cambricon, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: cambricon-device-plugin-static-pod
  namespace: kube-system
spec:
  serviceAccount: cambricon-device-plugin # comment to use default rbac
  hostPID: true
  hostIPC: true
  containers:
  - image: cambricon-device-plugin:v2.0.22
    name: cambricon-device-plugin-ctr
    command:
    - /usr/bin/k8s-device-plugin
    args:
    - --mode=default # device plugin mode: default, env-share, mim, topology-aware
    - --virtualization-num=1 # virtualization number for each MLU, used only env-share mode
    - --mlulink-policy=best-effort # MLULink topology policy: best-effort, guaranteed or restricted, used only in topology-aware mode
    - --cnmon-path=/usr/bin/cnmon # host machine cnmon path, must be absolute path. comment out this line if use-runtime is enabled
    - --log-level=info # log level: trace/debug/info/warn/error/fatal/panic" default:"info"
    - --enable-device-type # enable device registration with type info
    # - --node-label # uncomment to enable periodic checking and updating of node labels for MLU Devices, such as driver, mcu, model and cpu type
    # - --one-shot-for-node-label # uncomment to control node label only run once not periodically, only works when node label is enable
    # - --enable-console # uncomment to enable UART console device(/dev/ttyMS) in container
    # - --disable-health-check # uncomment to disable health check
    # - --mount-rpmsg # uncomment to mount RPMsg directory, will be deprecated in the near future
    livenessProbe:
      httpGet:
        path: /healthz
        port: 30107
      initialDelaySeconds: 60
      failureThreshold: 6
      periodSeconds: 30
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    securityContext:
      privileged: true
    volumeMounts:
    - name: device-plugin
      mountPath: /var/lib/kubelet/device-plugins
    - name: pod-resources
      mountPath: /var/lib/kubelet/pod-resources
    - name: dev
      mountPath: /dev
    - name: cndev-lib
      mountPath: /host/usr/lib
    - name: cndev-lib64
      mountPath: /host/usr/lib64
    - name: host-proc
      mountPath: /host/proc
      # mount /etc/cambricon if dynamic-smlu mode is enabled
      # - name: restore-cfg
      #   mountPath: /etc/cambricon
  volumes:
  - name: device-plugin
    hostPath:
      path: /var/lib/kubelet/device-plugins
  - name: pod-resources
    hostPath:
      path: /var/lib/kubelet/pod-resources
  - name: dev
    hostPath:
      path: /dev
  - name: cndev-lib
    hostPath:
      path: /usr/lib
  - name: cndev-lib64
    hostPath:
      path: /usr/lib64
  - name: host-proc
    hostPath:
      path: /proc
  # mount /etc/cambricon if dynamic-smlu mode is enabled
  # - name: restore-cfg
  #   hostPath:
  #     path: /etc/cambricon
