# Copyright 2020 Cambricon, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: binpack-n1
  labels:
    app: binpack-n1
spec:
  replicas: 1
  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: binpack-1
  template: # define the pods specifications
    metadata:
      labels:
        app: binpack-1
    spec:
      containers:
      - name: binpack-1
        image: ubuntu:22.04
        command: ["sleep"]
        args: ["100000"]
        resources:
          limits:
            cambricon.com/mlu: "1" #comment and set device bellow to use device with type info
            #cambricon.com/mlu.share: "1" #uncomment to use device with env-share mode
            #cambricon.com/mlu.mim-2m.8gb: "1" #uncomment to use device with mim mode
            #cambricon.com/mlu370: "1" #uncomment to use device with type info
            #cambricon.com/mlu370.share: "1" #uncomment to use device with type info with env-share mode
            #cambricon.com/mlu370.mim-2m.8gb: "1" #uncomment to use device with type info with mim mode
