nameOverride: "cambricon-device-plugin"
fullnameOverride: "cambricon-device-plugin-daemonset"
namespaceOverride: "kube-system"
selectorLabelsOverride: {}

allowDefaultNamespace: false

imagePullSecrets: []
image:
  repository: cambricon-device-plugin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

updateStrategy:
  type: RollingUpdate

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations:
# This toleration is deprecated. Kept here for backward compatibility
# See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
- key: CriticalAddonsOnly
  operator: Exists
- key: cambricon.com/mlu
  operator: Exists
  effect: NoSchedule

# Mark this pod as a critical add-on; when enabled, the critical add-on
# scheduler reserves resources for critical add-on pods so that they can
# be rescheduled after a failure.
# See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
priorityClassName: "system-node-critical"

runtimeClassName: null

devicePlugin:
  enabled: true

livenessProbe:
  httpGet:
    path: /healthz
    port: 30107
  initialDelaySeconds: 60
  failureThreshold: 6
  periodSeconds: 30

args:
- --mode=default # device plugin mode: default, env-share, mim, topology-aware
- --virtualization-num=1 # virtualization number for each MLU, used only in env-share mode, set to 110 to support multi cards per container in env-share mode
- --mlulink-policy=best-effort # MLULink topology policy: best-effort, guaranteed or restricted, used only in topology-aware mode
- --cnmon-path=/usr/bin/cnmon # host machine cnmon path, must be absolute path. comment out this line if use-runtime is enabled
- --log-level=info # log level: trace/debug/info/warn/error/fatal/panic" default:"info"
- --enable-device-type # enable device registration with type info
# - --node-label # uncomment to enable periodic checking and updating of node labels for MLU Devices, such as driver, mcu, model and cpu type
# - --one-shot-for-node-label # uncomment to control node label only run once not periodically, only works when node label is enable
# - --enable-console # uncomment to enable UART console device(/dev/ttyMS) in container
# - --disable-health-check # uncomment to disable health check
# - --mount-rpmsg # uncomment to mount RPMsg directory, will be deprecated in the near future

volumeMounts:
- name: device-plugin
  mountPath: /var/lib/kubelet/device-plugins
- name: pod-resources
  mountPath: /var/lib/kubelet/pod-resources
- name: dev
  mountPath: /dev
- name: cndev-lib
  mountPath: /host/usr/lib
- name: host-proc
  mountPath: /host/proc
  # mount /etc/cambricon if dynamic-smlu mode is enabled
  # - name: restore-cfg
  #   mountPath: /etc/cambricon

volumes:
- name: device-plugin
  hostPath:
    path: /var/lib/kubelet/device-plugins
- name: pod-resources
  hostPath:
    path: /var/lib/kubelet/pod-resources
- name: dev
  hostPath:
    path: /dev
- name: cndev-lib
  hostPath:
    path: /usr/lib
- name: host-proc
  hostPath:
    path: /proc

# mount /etc/cambricon if dynamic-smlu mode is enabled
# - name: restore-cfg
#   hostPath:
#     path: /etc/cambricon
