---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "device-plugin.name" . }}
  namespace: {{ include "device-plugin.namespace" . }}
  labels:
    {{- include "device-plugin.labels" . | nindent 4 }}
