---
name: Release Helm Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write # Required to create releases
  id-token: write # Needed for creating releases with GitHub Actions

jobs:
  release-helm-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.13.3'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: install

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: device-plugin/deploys/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"